### PR TITLE
add cython implementations of computationally expensive functions

### PR DESCRIPTION
**Pull request by FlorianRingbeckIsea**
Dear Valdecy,

thanks a lot for providing this library.
I noticed, that the import of large datasets can take some time.
To improve the import performance, I implemented some critical functions in cython.

It would be great, if you could review, test and merge the code.
Attached, you can also finde a small script to test the changes with a wos-dataset.

Best regards
Florian
[test.zip](https://github.com/Valdecy/pyBibX/files/14560841/test.zip)

### CODE REVIEW

**Comment by Valdecy** [comment]
Thank you so much! I will have a look and come back to you

**Comment by PabloPacheco** [comment]
Hi Dear Valdecy, thanks for the great tool. One question, is there a way to export plotly graphics in html format? I need it to use them in a presentation I'm making in reveal.js

**Comment by DanielSeRo1** [comment]
Hi! I am Daniel Serrano Robles, a student of the Master's degree in Information Design and Visualization from Mexico. I am currently conducting a bibliometric study on video game design and historical knowledge, the topic of my thesis. For this, I am using the pyBibx library that you published on GitHub. It is a great tool for my analysis, but I found some problems and difficulties in some parts when running the library in a Colab notebook.

I would say that the most important thing is in the Sankey Diagram section and the map of world academic production on the topic of the bibliometric study. I compile a Scopus database from 2000 to 2024 using the following boolean operators in the title, abstract and keywords:

( "game design" OR "serious game" OR "video game" ) AND ( "history" OR "cultural heritage" )

The Sankey Diagram should recognize the countries related to the studies in the database. According to the analytical tools of the Scopus search, most of them are related to the United States of America, but the Colab notebook with pyBibx shows other countries. It is alarming that the Colab shows a large percentage of studies with the label "Unknown". I suspect that this large number of unknown country studies are in fact all studies related to the United States. And the same goes for institutions. Colab shows many unknown institutions, but Scopus has a detailed list of institutions related to the studies in the database. 

Could you please help me with this? I don't know if I'm doing something wrong or if there is a problem with the library code. If you need it, I share the Colab Notebook and the Drive folder for the database archive. The database archive file name is: "hist + game 24.bib" Regards!

Colab Notebook link: https://colab.research.google.com/drive/1IonQ1kf-8v3WvKEWlm3vCC2ykdg6ukmb?usp=sharing

Drive folder link: https://drive.google.com/drive/folders/1SxztZaHdl5-ctIVdVXZe0T6QeaGw0nau?usp=drive_link

I'm sorry if this is not the space to comment, but I couldn't find a better place to do it.

Daniel Serrano Robles

**Comment by Valdecy** [comment]
Dear Daniel,

Thank you very much for reaching out and for your detailed explanation regarding the issues you encountered. I appreciate you taking the time to provide feedback and share your Colab Notebook and database archive links.

I’m pleased to let you know that I have corrected the issue in pyBibx version 4.5.7. The problem with the many “Unknown” labels arose because of metadata formatting inconsistencies. For example, when the metadata for authors and their corresponding countries is formatted as: 

- **Case 1:**  
  `[Author 1, Author 2] ; [Turkey, Brazil]`  
  The parser correctly associates Author 1 with Turkey and Author 2 with Brazil.

- **Case 2:**  
  `[Author 1, Author 2] ; [Brazil]`  
  The parser would previously assign Author 1 to Brazil and mark Author 2 as “Unknown.”  
  This ambiguity—whether Author 1 or Author 2 provided the country, or if both are from Brazil—introduced too much room for misinterpretation.

In the new version, the program now prioritizes the later entry when such a discrepancy occurs, thereby mitigating the number of “Unknown” labels and offering a more accurate reflection of the metadata.

Regarding the **Sankey Diagram** function:

sankey_diagram(self, view='browser', entry=['aut', 'cout', 'inst', 'jou', 'kwa', 'kwp', 'lan'], rmv_unknowns=False, topn=None)

- **view:**  
  Determines where the plot is rendered.  
  Options include `'browser'` (to display in your preferred browser) or, if supported, `'notebook'` (to display within your notebook).

- **entry:**  
  A list of keys that define the sequential nodes in the diagram. These keys can be any combination of the following:  
  - 'aut' (Authors)
  - 'cout' (Countries)
  - 'inst' (Institutions)
  - 'jou' (Journals)
  - 'kwa' (Authors_Keywords)
  - 'kwp' (Keywords_Plus)
  - 'lan' (Languages)

- **rmv_unknowns:**  
  A Boolean flag that determines whether relationships with unknown values are removed (if set to True) or kept with placeholder labels (if set to False).

- **topn:**  
  Optionally restricts the number of top entities to include in the format of a list of values per pairs.

You can find examples of how to use this function in the provided Colab Notebook.

Thank you again for your valuable feedback.

Best regards,

Valdecy Pereira

**Pull request closed without merging**
